name: CD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
#  pull_request:
#    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
      runs-on: ubuntu-latest
      
    # Steps representan la secuencia en la que se ejecuta el job (tarea/trabajo)
      
      steps:
 
      - name: Remote SSH Commands
        uses: fifsky/ssh-action@v0.0.4
        with:
         command: |
                 cd /var/www/proyectos_clase/
                 rm -rf panaderia
                 git clone https://${{secrets.GIT_TOKEN}}@github.com/danielperez9430/panaderia.git
         host: ${{secrets.SERVER_IP}}
         user: ${{secrets.SSH_USERNAME}}
         port: ${{secrets.SERVER_PORT}}
         key: ${{secrets.SSH_DEPLOY_PRIVATE_KEY}}